### ISSUE TITLE
Inner links inside nodes not working.

### ISSUE THREAD

**Issue by franzz2000** [ghbore/flowchartjs#11]
Hi,

I'm trying to add an inner link to the flowchart, but it doesn't work.

    <flowchartjs default>

    st=>start: start:>documentation:start

    ed=>end: Acepta

    st->ed

    </flowchartjs>

I don't know if it's possible or am I doing something wrong.

Thank you,

Franz Jimeno

**Comment by ghbore** [comment]
Hi Franz,

Sorry for the late reply. I have tried different ways and found the easiest way is to change the `allowedTypes` to allow `substition` syntax type inside the `<flowchartjs>` block. Then any `substition` syntax could be used, for example a innerlink `[[documentation:start]]` (double brackets are important).

I have created a new branch **enable_substition** to implement this enhancement but have not directly updated on the 'master', because
1. I have not fully tested whether this enhancement has any conflict with _flowchartjs_ syntax, and the syntax of _flowchartjs_ is rather complex
2. To enable this enhancement, the dokuwiki should set `userewrite` to 'Dokuwiki internal' and enable `useslash` (these configurations can be found through **Configuration Manager**)

So if you like this feature, you can update your local plugin to this  **enable_substition** branch, or just update the **syntax.php** file, or just insert `function getAllowedTypes() { return array('substition'); }` on line 22 of **syntax.php** file.

Best,
Hua

**Comment by vic-t** [comment]
Hi @ghbore, 

I changed my syntax php the way you mentioned but this seems to have no effect. Here a small extract from my syntax.php: 

```
class syntax_plugin_flowchartjs extends DokuWiki_Syntax_Plugin {

        function getType(){ return 'protected'; }
        function getAllowedTypes(){ return array('substitution'); }
        function getPType(){ return 'block'; }
        function getSort(){ return 999; }

```

If I understood you correctly, it's not necessary to also set `userewrite` and `useslash` when syntax.php was changed. That's only necessary if one is going to use the new branch.

**Comment by ghbore** [comment]
Hi @vic-t , sorry for the confusion! Besides the modification of the `syntax.php` file, the configurations of `userewrite` and `useslash` seem to be also mandatory. This is one reason why I did not merge this enhancement to the master branch.

**Comment by vic-t** [comment]
Hi Hua, 

Thank you for replying. It would really be a massive improvement if local links could be used in a flowchart but I'm a bit wary of changing these settings for the whole site. 

I was comparing your plugin with the plugin flowcharts which is based on mermaid.js. While mermaid.js is really great when it comes to creating gantt charts or UML diagrams, I think flowchartjs does a better job for regular flowcharts. However, unlike your plugin, the flowcharts plugin does manage inner links. Maybe there are some ideas there that could be easily introduced in your plugin? It's just a suggestion anyway. 🙂

**Comment by ghbore** [comment]
Thank you for your advice @vic-t ! [flowcharts](https://github.com/jakob1111/dokuwiki-plugin-flowcharts/) is really a good reference. I will try to incorporate their ideas into this one and find a way to avoid the syntax conflicts with [flowchart.js](https://flowchart.js.org/)

**Comment by vic-t** [comment]
Here a link to the PR that added this functionality to flowcharts: https://github.com/jakob1111/dokuwiki-plugin-flowcharts/pull/3
