### ISSUE TITLE
Flowcharts not working with Igor

### ISSUE THREAD

**Issue by diadz** [ghbore/flowchartjs#13]
I upgraded my Dokuwiki installation to Igor and it resulted in flowcharts not loading. I rolled back to Hogfather and flowcharts are working once again. It would be great if whatever adjustments are required for compatibility with Igor could be made.

**Comment by ghbore** [comment]
Hi @diadz, apologize for the failure to maintain this plugin for years. This issue may be related to #14, and now after I have implemented an update, it should work now. And I just tested it again with Igor version (using docker image linuxserver/dokuwiki:version-2022-07-31a), it indeed works. Let me know if the issue is still there.

![image](https://github.com/ghbore/flowchartjs/assets/9670777/306ec394-4163-4a3e-8d4e-fbe628f9060a)
